const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');

test('all card links open in a safe new tab',()=>{assert.match(app,/link\.target='_blank'/);assert.match(app,/link\.rel='noopener noreferrer'/)});
test('categories can be added and deleted through saved history',()=>{assert.match(app,/delete-category-button/);assert.match(app,/deleteCategory\(/);assert.match(app,/removedCategories/);assert.match(app,/commitConfig\(config=>/)});
test('empty categories remain visible as card move destinations',()=>{assert.match(app,/groupByCategory\(state\.apps,state\.config\.categories,state\.config\.orders,true\)/);assert.match(app,/is-empty-category/);assert.match(app,/ここへカードを移動できます/)});
test('left category list supports card drops and category reordering',()=>{assert.match(html,/class="portal-sidebar"/);assert.match(html,/aria-label="項目一覧"/);assert.match(app,/application\/x-step-category/);assert.match(app,/reorderCategory\(/);assert.match(app,/moveCategory\(/);assert.match(app,/moveApp\(event\.dataTransfer\.getData\('application\/x-step-app'\)/)});
test('left list mirrors global search and accepts explicit app card drops',()=>{assert.match(html,/id="categorySearch"/);assert.match(html,/category-search-wrap/);assert.match(app,/application\/x-step-app/);assert.match(app,/syncSearch\(/);assert.match(app,/byId\('searchInput'\)\.value=value/);assert.match(app,/categoryNavEmpty/)});
test('category drag uses a dedicated handle so the full item remains a card drop target',()=>{assert.match(app,/category-drag-handle/);assert.match(app,/handle\.addEventListener\('dragstart'/);assert.doesNotMatch(app,/navItem\.draggable=state\.organizing/)});

test('起動時は認証確認画面だけを表示する',()=>{assert.match(html,/body data-state="checking"/);assert.match(html,/id="loginScreen" hidden/);assert.match(html,/id="appShell" hidden/);assert.match(app,/setScreen\('checking'\)/)});
test('スタッフ共通認証と台帳・機能カタログを再利用する',()=>{assert.match(app,/api\('staffLogin'/);assert.match(app,/api\('getSystemRegistry'\)/);assert.match(app,/workspace-apps\.json/);assert.match(app,/app-catalog\.json/);assert.match(app,/mergeRegistrySources/);assert.match(app,/mergeCatalogSources/);assert.match(app,/stepStaffAppAuth/);assert.match(app,/\['2','3','4'\]/)});
test('アプリカードは通常のリンクを使う',()=>{assert.match(html,/<a class="app-link">/);assert.match(app,/link\.href=app\.url/);assert.doesNotMatch(app,/window\.location/)});
test('Googleスプレッドシートのカードは専用SVGアイコンを表示する',()=>{assert.match(app,/sheet-app-icon/);assert.match(app,/Google スプレッドシート/);assert.match(app,/sheet-grid/)});
test('Sheetsカードは専用のSheetsマークを表示する',()=>{assert.match(html,/class="app-icons"/);assert.match(html,/class="sheet-app-icon"/);assert.match(app,/sheet\.hidden=app\.iconType!==\'google-sheet\'/)});
test('Google Sheets mark is positioned at the card bottom right',()=>{const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');assert.match(css,/\.app-card \.sheet-app-icon\{position:absolute;right:42px;bottom:10px/);assert.match(css,/pointer-events:none/)});
test('business portal visual hierarchy keeps favorites first and categories compact',()=>{assert.match(html,/class="portal-sidebar"/);assert.match(html,/必要なアプリへ、ここからすぐアクセスできます。/);assert.ok(html.indexOf('id="favoriteSection"')<html.indexOf('class="all-apps-section"'));assert.match(app,/categoryDescription\(/);assert.match(css,/featured-grid\{grid-template-columns:repeat\(5/)});
test('management controls stay inside a dedicated mode',()=>{assert.match(html,/id="managementButton"/);assert.match(html,/id="managementPanel" hidden/);assert.match(html,/id="finishManagementButton"/);assert.match(app,/setManagementMode\(/);assert.match(css,/app-shell:not\(\.is-admin-mode\)/)});
test('search remains a popover over the home screen',()=>{assert.match(html,/class="search-popover"/);assert.match(html,/アプリ名・用途から検索/);assert.doesNotMatch(app,/defaultSections'\)\.hidden=active/);assert.match(app,/slice\(0,8\)/)});
test('favicon and PWA icon set is complete',()=>{for(const name of ['favicon.svg','favicon.ico','favicon-16x16.png','favicon-32x32.png','apple-touch-icon.png','icon-192.png','icon-512.png','manifest.webmanifest'])assert.ok(fs.existsSync(path.join(root,name)),name);assert.match(html,/rel="manifest"/);assert.match(html,/favicon-16x16\.png/);const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));assert.deepEqual(manifest.icons.map(icon=>icon.sizes),['192x192','512x512'])});
test('項目編集・カード移動・端末指定を端末へ保存する',()=>{assert.match(html,/id="settingsButton"/);assert.match(html,/id="organizeButton"/);assert.match(html,/aria-label="利用端末"/);assert.match(app,/stepWorkspaceConfigV1/);assert.match(app,/moveApp\(/);assert.match(app,/setDevice\(/);assert.match(app,/showModal\(\)/);assert.match(app,/dragstart/)});
test('戻る・進むと同一項目内の並べ替えを提供する',()=>{assert.match(html,/id="undoButton"/);assert.match(html,/id="redoButton"/);assert.match(html,/class="move-up"/);assert.match(html,/class="move-down"/);assert.match(app,/undoConfig\(/);assert.match(app,/redoConfig\(/);assert.match(app,/reorderApp\(/)});
test('カード追加とアーカイブ・復元・完全削除を提供する',()=>{for(const id of ['addCardButton','archiveButton','addCardDialog','archiveDialog','archiveList'])assert.match(html,new RegExp(`id="${id}"`));assert.match(app,/addCard\(/);assert.match(app,/archiveApp\(/);assert.match(app,/restoreApp\(/);assert.match(app,/permanentlyDeleteApp\(/);assert.match(app,/この操作は戻せません/)});
test('明示ログアウトで認証情報だけを削除する',()=>{assert.match(app,/api\('logoutSystemPortal'\)/);assert.match(app,/removeItem\(AUTH_KEY\)/);assert.match(app,/removeItem\(STAFF_CODE_KEY\)/);assert.match(app,/removeItem\(STAFF_PASSWORD_KEY\)/)});
test('お気に入りと最近使ったアプリを端末へ保存する',()=>{assert.match(app,/stepWorkspaceFavoritesV1/);assert.match(app,/stepWorkspaceRecentV1/);assert.match(app,/slice\(0,5\)/)});
test('開発情報を画面文言に露出しない',()=>{for(const term of ['Apps Script Project ID','commit SHA','Worker名','D1','R2','API URL','調査メモ'])assert.doesNotMatch(html,new RegExp(term))});
