const test=require('node:test');
const assert=require('node:assert/strict');
const core=require('../core.js');

test('deleted categories stay hidden and future cards fall back safely',()=>{const config=core.normalizeWorkspaceConfig({removedCategories:['billing']});assert.equal(config.categories.some(item=>item.id==='billing'),false);assert.deepEqual(config.removedCategories,['billing']);const [app]=core.applyWorkspaceConfig([{id:'new-billing',categoryId:'billing'}],config);assert.equal(app.categoryId,config.categories[0].id)});
test('category order is preserved with every card grouped under it',()=>{const config=core.normalizeWorkspaceConfig({categories:[{id:'teacher',label:'講師'},{id:'student',label:'生徒'}]});assert.deepEqual(config.categories.slice(0,2).map(item=>item.id),['teacher','student']);const apps=core.applyWorkspaceConfig([{id:'lesson',categoryId:'teacher'},{id:'grade',categoryId:'student'}],config);const groups=core.groupByCategory(apps,config.categories,{},true);assert.deepEqual(groups.slice(0,2).map(group=>[group.category.id,group.apps[0].id]),[['teacher','lesson'],['student','grade']])});

const records=[
  {ID:'billing','システム名':'請求管理システムV3.1（学費計算・請求データ作成）','利用者向けURL':'https://example.com/billing','概要':'技術情報を含む長い説明 Apps Script'},
  {ID:'invoice','システム名':'STEP請求書PDF作成・配信システム','利用者向けURL':'https://example.com/invoice'},
  {ID:'message','システム名':'STEP配信システム','利用者向けURL':'https://example.com/message','概要':'生徒・保護者への連絡'},
  {ID:'teacher','システム名':'講師ポータル','利用者向けURL':'https://example.com/teacher'},
  {ID:'grades','システム名':'成績管理','利用者向けURL':'https://example.com/grades'}
];

test('台帳の正式URLを優先してアプリへ変換する',()=>{const app=core.toApp(records[0]);assert.equal(app.url,'https://example.com/billing');assert.equal(app.categoryId,'billing')});
test('請求管理と請求書PDFを別アプリとして保持する',()=>{const apps=core.buildApps(records);assert.notEqual(apps[0].id,apps[1].id);assert.equal(apps.filter(app=>app.categoryId==='billing').length,2)});
test('日本語の名前・説明・キーワードでリアルタイム検索できる',()=>{const apps=core.buildApps(records);assert.deepEqual(core.filterApps(apps,'請求').map(app=>app.id),['billing','invoice']);assert.ok(core.filterApps(apps,'はいしん').some(app=>app.id==='message'))});
test('用途別に5分類する',()=>{const apps=core.buildApps(records);assert.equal(apps.find(app=>app.id==='message').categoryId,'contact');assert.equal(apps.find(app=>app.id==='teacher').categoryId,'teacher');assert.equal(apps.find(app=>app.id==='grades').categoryId,'student')});
test('説明文に請求が含まれても講師予定は講師へ分類し請求検索へ混ぜない',()=>{const app=core.toApp({ID:'schedule','システム名':'講師予定・夏休み出勤登録','概要':'請求処理と連携する講師予定'});assert.equal(app.categoryId,'teacher');assert.equal(core.filterApps([app],'請求').length,0)});
test('出退くんQRは台帳分類に講師が含まれても連絡・受付へ分類する',()=>{const app=core.toApp({ID:'qr','システム名':'出退くんQR作成・読取','分類':'生徒・講師'});assert.equal(app.categoryId,'contact')});
test('既定のお気に入りは主要業務を最大5件選ぶ',()=>{const ids=core.defaultFavoriteIds(core.buildApps(records));assert.ok(ids.includes('billing'));assert.ok(ids.includes('invoice'));assert.ok(ids.includes('message'));assert.ok(ids.length<=5)});
test('HTTP以外や要確認の値をリンクにしない',()=>{assert.equal(core.firstUrl({'利用者向けURL':'要確認'}),'');assert.equal(core.firstUrl({'利用者向けURL':'javascript:alert(1)'}),'')});
test('GoogleスプレッドシートURLだけを専用アイコン対象にする',()=>{const sheet=core.toApp({ID:'sheet','システム名':'受付カード','利用者向けURL':'https://docs.google.com/spreadsheets/d/example/edit'});const page=core.toApp(records[4]);assert.equal(sheet.iconType,'google-sheet');assert.equal(page.iconType,'category');assert.equal(core.isGoogleSheetUrl('https://docs.google.com/document/d/example/edit'),false)});
test('activeだけを表示してhiddenとlegacyを除外する',()=>{const apps=core.buildApps([{id:'active',displayName:'現行',productionUrl:'https://example.com/a',status:'active'},{id:'hidden',displayName:'非表示',productionUrl:'https://example.com/b',status:'hidden'},{id:'legacy',displayName:'旧版',productionUrl:'https://example.com/c',status:'legacy'}]);assert.deepEqual(apps.map(app=>app.id),['active'])});
test('機能データの親システムと利用制御を保持する',()=>{const app=core.toApp({id:'report',displayName:'授業報告',description:'授業後に報告',category:'teacher',productionUrl:'https://example.com/?view=attendance',parentSystem:'講師ポータル',keywords:['コマ数'],favorite:false,recent:false,status:'active'});assert.equal(app.parentSystem,'講師ポータル');assert.equal(app.categoryId,'teacher');assert.equal(app.favoriteEnabled,false);assert.equal(app.recentEnabled,false);assert.equal(core.filterApps([app],'コマ数').length,1)});
test('query parameterで分かれる内部画面は別アプリとして保持する',()=>{const apps=core.buildApps([{id:'attendance',displayName:'授業報告',productionUrl:'https://example.com/?view=attendance',status:'active'},{id:'qr',displayName:'QR',productionUrl:'https://example.com/?view=qr',status:'active'}]);assert.equal(apps.length,2)});
test('カタログの同一URLと置換対象を台帳一覧から重複排除する',()=>{const registry=[{'正式名称':'STEP配信システム','利用者向けURL':'https://example.com/message'},{'正式名称':'受付カード読み取り','利用者向けURL':'https://example.com/sheet'}];const catalog=[{id:'message',displayName:'STEP配信システム',productionUrl:'https://example.com/message',status:'active'},{id:'card',displayName:'受付カード読取',productionUrl:'https://example.com/card',replaces:['受付カード読み取り'],status:'active'}];const apps=core.buildApps(core.mergeCatalogSources(registry,catalog));assert.deepEqual(apps.map(app=>app.id),['message','card'])});
test('SYSTEM_REGISTRYの正式一覧を解析する',()=>{const md='| 正式名称 | 状態 | 利用者向け本番URL | リポジトリ |\n|---|---|---|---|\n| 成績管理 | 本番 | https://example.com/grades | [repo](https://github.com/x/y) |\n| 生徒マスタ | 本番 | 要確認 | 要確認 |\n';const items=core.parseRegistryMarkdown(md);assert.equal(items.length,2);assert.equal(items[0]['正式名称'],'成績管理');assert.equal(items[0]['利用者向けURL'],'https://example.com/grades')});
test('Markdown正式一覧へAPI詳細をマージし不足登録も残す',()=>{const api=[{'システム名':'成績管理','概要':'成績を管理','利用者向けURL':'https://example.com/grades'}];const markdown=[{'正式名称':'成績管理','状態':'本番','利用者向けURL':'https://example.com/grades'},{'正式名称':'過去問保管DB','状態':'本番','利用者向けURL':'https://example.com/past'}];const merged=core.mergeRegistrySources(api,markdown);assert.equal(merged.length,2);assert.equal(merged[0]['概要'],'成績を管理');assert.equal(merged[1]['正式名称'],'過去問保管DB')});
test('項目名・追加項目・カード移動・端末指定を適用する',()=>{const apps=core.buildApps([{id:'sheet','システム名':'講師マスター','利用者向けURL':'https://docs.google.com/spreadsheets/d/x/edit','分類':'講師'}]);const config=core.normalizeWorkspaceConfig({categories:[{id:'teacher',label:'先生・給与'},{id:'custom-school',label:'校舎運営'}],assignments:{sheet:'custom-school'},orders:{'custom-school':['sheet']},devices:{sheet:'mobile'}});const customized=core.applyWorkspaceConfig(apps,config)[0];assert.equal(config.categories.find(item=>item.id==='teacher').label,'先生・給与');assert.equal(customized.categoryId,'custom-school');assert.equal(customized.categoryLabel,'校舎運営');assert.equal(customized.initial,'校');assert.equal(customized.device,'mobile');assert.equal(customized.iconType,'google-sheet')});
test('不正な項目と端末指定は保存設定から除外する',()=>{const config=core.normalizeWorkspaceConfig({categories:[{id:'bad',label:'不正'}],assignments:{a:'bad'},devices:{a:'watch'}});assert.equal(config.categories.some(item=>item.id==='bad'),false);assert.deepEqual(config.assignments,{});assert.deepEqual(config.devices,{})});
test('カード順序を項目ごとに反映する',()=>{const apps=core.applyWorkspaceConfig(core.buildApps([{id:'a','システム名':'A','利用者向けURL':'https://example.com/a',category:'teacher'},{id:'b','システム名':'B','利用者向けURL':'https://example.com/b',category:'teacher'}]),core.defaultWorkspaceConfig());const config=core.defaultWorkspaceConfig();config.orders.teacher=['b','a'];const group=core.groupByCategory(apps,config.categories,config.orders).find(item=>item.category.id==='teacher');assert.deepEqual(group.apps.map(app=>app.id),['b','a'])});
test('追加カードとアーカイブ・完全削除情報を正規化する',()=>{const config=core.normalizeWorkspaceConfig({customApps:[{id:'custom-card-1',displayName:'追加',productionUrl:'https://example.com/custom',category:'contact'}],archived:['custom-card-1','custom-card-1'],deleted:['old']});assert.equal(config.customApps.length,1);assert.equal(config.customApps[0].status,'active');assert.deepEqual(config.archived,['custom-card-1']);assert.deepEqual(config.deleted,['old'])});
